# Generated by Django 5.2 on 2025-09-08 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Birim Adı')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Kısaltma')),
            ],
            options={
                'verbose_name': 'Ölçü Birimi',
                'verbose_name_plural': 'Ölçü Birimleri',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Malzeme Adı')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Stok Miktarı')),
                ('alert_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Uyarı Eşiği')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.business', verbose_name='İşletme')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure', verbose_name='Ölçü Birimi')),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IngredientStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INITIAL', 'Başlangıç Stoku'), ('ADDITION', 'Stok Girişi (Alım)'), ('SALE', 'Satıştan Düşüm'), ('RETURN', 'İade'), ('ADJUSTMENT_IN', 'Sayım Düzeltme (Fazla)'), ('ADJUSTMENT_OUT', 'Sayım Düzeltme (Eksik)'), ('WASTAGE', 'Zayiat/Fire')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.ingredient')),
                ('related_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_movements', to='core.orderitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Malzeme Stok Hareketi',
                'verbose_name_plural': 'Malzeme Stok Hareketleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Gerekli Miktar')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='core.ingredient', verbose_name='Malzeme')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='core.menuitemvariant', verbose_name='Ürün Varyantı')),
            ],
            options={
                'verbose_name': 'Reçete Kalemi',
                'verbose_name_plural': 'Reçete Kalemleri',
                'unique_together': {('variant', 'ingredient')},
            },
        ),
    ]
