# Generated by Django 5.2 on 2025-10-06 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attendancerecord_check_in_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinlocation',
            name='radius_meters',
            field=models.FloatField(default=100.0, help_text='1 ile 10000 metre arasında olmalıdır', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000.0)], verbose_name='Yarıçap (Metre)'),
        ),
    ]
