# Generated by Django 5.2 on 2025-09-08 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unitofmeasure_ingredient_ingredientstockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Birim Maliyet Fiyatı'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tedarikçi Adı')),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True, verbose_name='Yetkili Kişi')),
                ('email', models.EmailField(blank=True, help_text='Düşük stok bildirimleri bu adrese gönderilir.', max_length=255, null=True, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.business', verbose_name='İşletme')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alım Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('invoice_image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Fatura Görseli URL')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Toplam Tutar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.business', verbose_name='İşletme')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Alım Faturası',
                'verbose_name_plural': 'Alım Faturaları',
                'ordering': ['-order_date'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='core.supplier', verbose_name='Tedarikçi'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Birim Alış Fiyatı (Maliyet)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.ingredient', verbose_name='Malzeme')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder', verbose_name='Alım Faturası')),
            ],
            options={
                'verbose_name': 'Alım Faturası Kalemi',
                'verbose_name_plural': 'Alım Faturası Kalemleri',
                'unique_together': {('purchase_order', 'ingredient')},
            },
        ),
    ]
