# Generated by Django 5.2 on 2025-09-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient_low_stock_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='low_stock_notification_sent',
        ),
    ]
