# Generated by Django 5.2 on 2025-09-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ingredient_low_stock_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='low_stock_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Düşük Stok Bildirimi Gönderildi'),
        ),
    ]
