# Generated by Django 5.2 on 2025-09-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient_low_stock_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='related_order',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='variant',
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Envanter Kalemi', 'verbose_name_plural': 'Envanter Kalemleri'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Bu ürünün stoğu takip edilecek mi? Pasif ise miktar ve uyarılar dikkate alınmaz.', verbose_name='Stok Takibi Aktif'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Envanter Kalemi Adı'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
