# Generated by Django 5.2 on 2025-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_stockmovement_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about_us',
            field=models.TextField(blank=True, help_text="Web sitesinde görünecek 'Hakkımızda' bölümü içeriği.", verbose_name='Hakkımızda Metni'),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_details',
            field=models.JSONField(blank=True, default=dict, help_text='Web sitesinde gösterilecek e-posta, telefon, sosyal medya gibi bilgiler. JSON formatında.', verbose_name='Web Sitesi İletişim Bilgileri'),
        ),
        migrations.AddField(
            model_name='business',
            name='website_slug',
            field=models.SlugField(blank=True, help_text='İşletmenin herkese açık web sitesi için benzersiz URL adresi. Boş bırakılırsa otomatik oluşturulur.', max_length=120, null=True, unique=True, verbose_name='Web Sitesi URL Adresi'),
        ),
    ]
