# Generated by Django 5.2 on 2025-09-13 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_stockmovement_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.CreateModel(
            name='BusinessWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='Hakkımızda', max_length=200, verbose_name='Hakkımızda Başlığı')),
                ('about_description', models.TextField(blank=True, null=True, verbose_name='Hakkımızda Açıklaması')),
                ('about_image', models.URLField(blank=True, null=True, verbose_name='Hakkımızda Görseli')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('contact_address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('contact_working_hours', models.TextField(blank=True, null=True, verbose_name='Çalışma Saatleri')),
                ('map_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Enlem')),
                ('map_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Boylam')),
                ('map_zoom_level', models.IntegerField(default=15, verbose_name='Harita Zoom Seviyesi')),
                ('website_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Web Sitesi Başlığı')),
                ('website_description', models.TextField(blank=True, null=True, verbose_name='Web Sitesi Açıklaması')),
                ('website_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Anahtar Kelimeler')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Ana Renk')),
                ('secondary_color', models.CharField(default='#10B981', max_length=7, verbose_name='İkincil Renk')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('show_menu', models.BooleanField(default=True, verbose_name='Menüyü Göster')),
                ('show_contact', models.BooleanField(default=True, verbose_name='İletişim Bilgilerini Göster')),
                ('show_map', models.BooleanField(default=True, verbose_name='Haritayı Göster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='core.business')),
            ],
            options={
                'verbose_name': 'İşletme Web Sitesi',
                'verbose_name_plural': 'İşletme Web Siteleri',
                'db_table': 'core_business_website',
            },
        ),
    ]
