# Generated by Django 5.2 on 2025-09-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_business_about_us_business_contact_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='business',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='business',
            name='website_slug',
        ),
    ]
