# Generated by Django 5.2 on 2025-09-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_business_slug_businesswebsite'),
        ('core', '0009_remove_business_about_us_and_more'),
    ]

    operations = [
    ]
