# Generated by Django 5.2 on 2025-09-14 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20250913_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswebsite',
            name='allow_online_ordering',
            field=models.BooleanField(default=False, verbose_name='Online Siparişe İzin Ver'),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='allow_reservations',
            field=models.BooleanField(default=False, verbose_name='Online Rezervasyona İzin Ver'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Müşteri Adı Soyadı')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Müşteri Telefon')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Müşteri E-posta')),
                ('reservation_time', models.DateTimeField(verbose_name='Rezervasyon Tarihi ve Saati')),
                ('party_size', models.PositiveIntegerField(verbose_name='Kişi Sayısı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Özel Notlar')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('seated', 'Oturdu')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.business', verbose_name='İşletme')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.table', verbose_name='Masa')),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
                'ordering': ['-reservation_time'],
                'unique_together': {('table', 'reservation_time')},
            },
        ),
    ]
