# Generated by Django 5.2 on 2025-09-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_businesswebsite_allow_online_ordering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.FloatField(blank=True, null=True, verbose_name='X Koordinatı'),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y Koordinatı'),
        ),
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.FloatField(default=0.0, verbose_name='Dönme Açısı (Derece)'),
        ),
        migrations.CreateModel(
            name='BusinessLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=800.0, help_text='Yerleşim planı tuvalinin genişliği')),
                ('height', models.FloatField(default=600.0, help_text='Yerleşim planı tuvalinin yüksekliği')),
                ('background_image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name="Arka Plan Görseli URL'i")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='core.business')),
            ],
            options={
                'verbose_name': 'İşletme Yerleşim Planı',
                'verbose_name_plural': 'İşletme Yerleşim Planları',
            },
        ),
        migrations.AddField(
            model_name='table',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables_on_layout', to='core.businesslayout'),
        ),
    ]
