# Generated by Django 5.2 on 2025-09-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_table_pos_x_table_pos_y_table_rotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Metin Etiketi'), ('shape', 'Şekil')], default='text', max_length=10)),
                ('pos_x', models.FloatField(default=50.0)),
                ('pos_y', models.FloatField(default=50.0)),
                ('width', models.FloatField(default=150.0)),
                ('height', models.FloatField(default=40.0)),
                ('rotation', models.FloatField(default=0.0, help_text='Dönme açısı (derece)')),
                ('style_properties', models.JSONField(default=dict, help_text="Öğenin stil özelliklerini içeren JSON. Örn: {'content': 'Deniz Tarafı', 'fontSize': 16, 'color': '#FFFFFF', 'shapeType': 'rectangle'}")),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='core.businesslayout')),
            ],
            options={
                'verbose_name': 'Yerleşim Planı Öğesi',
                'verbose_name_plural': 'Yerleşim Planı Öğeleri',
                'ordering': ['id'],
            },
        ),
    ]
