# Generated by Django 5.2 on 2025-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_layoutelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswebsite',
            name='about_image',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Hakkımızda Görseli'),
        ),
    ]
