# Generated by Django 5.2 on 2025-09-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_businesswebsite_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswebsite',
            name='theme_mode',
            field=models.CharField(choices=[('system', 'Sistem Varsayılanı'), ('light', 'Aydınlık Mod'), ('dark', 'Karanlık Mod')], default='system', max_length=10, verbose_name='Web Sitesi Teması'),
        ),
    ]
