# Generated by Django 5.2 on 2025-09-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_businesswebsite_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pos_integration_enabled',
            field=models.BooleanField(default=False, help_text='İşletme, ödemeleri entegre bir POS cihazı üzerinden mi alacak?', verbose_name='Fiziksel POS Entegrasyonu Aktif'),
        ),
    ]
