# Generated by Django 5.2 on 2025-09-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_business_pos_integration_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_terminal_id', models.CharField(help_text='Stripe, Adyen gibi ödeme sağlayıcısından alınan benzersiz terminal kimliği.', max_length=255, unique=True, verbose_name='Sağlayıcı Terminal ID')),
                ('name', models.CharField(help_text='Kullanıcının terminali tanıması için verdiği isim (örn: Kasa 1, Bar Terminali).', max_length=100, verbose_name='Terminal Adı')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif'), ('out_of_service', 'Servis Dışı')], default='active', max_length=20, verbose_name='Durum')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='core.business', verbose_name='İşletme')),
            ],
            options={
                'verbose_name': 'Ödeme Terminali',
                'verbose_name_plural': 'Ödeme Terminalleri',
                'ordering': ['name'],
            },
        ),
    ]
