# Generated by Django 5.2 on 2025-09-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_paymentterminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='pos_integration_enabled',
        ),
        migrations.RemoveField(
            model_name='businesswebsite',
            name='theme_mode',
        ),
        migrations.AlterField(
            model_name='businesswebsite',
            name='about_image',
            field=models.URLField(blank=True, null=True, verbose_name='Hakkımızda Görseli'),
        ),
        migrations.DeleteModel(
            name='PaymentTerminal',
        ),
    ]
