# Generated by Django 5.2 on 2025-09-23 19:42

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_business_pos_integration_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='payment_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Ödeme Sağlayıcı API Anahtarı'),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_provider',
            field=models.CharField(choices=[('none', 'Entegrasyon Yok'), ('iyzico', 'Iyzico'), ('paytr', 'PayTR')], default='none', max_length=20, verbose_name='Ödeme Sağlayıcı'),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_secret_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Ödeme Sağlayıcı Gizli Anahtarı'),
        ),
    ]
