# Generated by Django 5.2 on 2025-09-27 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şablon Adı')),
                ('icon_name', models.CharField(blank=True, help_text="Örn: 'local_dining', 'local_bar'", max_length=100, null=True, verbose_name='Flutter İkon Adı')),
                ('language', models.CharField(default='tr', help_text="Örn: 'tr', 'en'", max_length=5, verbose_name='Dil Kodu')),
            ],
            options={
                'verbose_name': 'Kategori Şablonu',
                'verbose_name_plural': 'Kategori Şablonları',
                'ordering': ['name'],
                'unique_together': {('name', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı Şablonu')),
                ('language', models.CharField(default='tr', max_length=5, verbose_name='Dil Kodu')),
                ('category_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_templates', to='templates.categorytemplate', verbose_name='Kategori Şablonu')),
            ],
            options={
                'verbose_name': 'Menü Ürünü Şablonu',
                'verbose_name_plural': 'Menü Ürünü Şablonları',
                'ordering': ['name'],
                'unique_together': {('category_template', 'name', 'language')},
            },
        ),
        migrations.CreateModel(
            name='VariantTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Varyant Adı')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Ana ürün fiyatı ile çarpılacak değer (örn: 1.3 = %30 artış)', max_digits=4, verbose_name='Fiyat Çarpanı')),
                ('icon_name', models.CharField(help_text="Örn: 'restaurant', 'local_cafe'", max_length=100, verbose_name='Flutter İkon Adı')),
                ('language', models.CharField(default='tr', max_length=5, verbose_name='Dil Kodu')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('category_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_templates', to='templates.categorytemplate', verbose_name='Kategori Şablonu')),
            ],
            options={
                'verbose_name': 'Varyant Şablonu',
                'verbose_name_plural': 'Varyant Şablonları',
                'ordering': ['category_template', 'display_order', 'name'],
                'unique_together': {('category_template', 'name', 'language')},
            },
        ),
    ]
