# Generated by Django 5.2 on 2025-09-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantTemplate',
        ),
    ]
