# Generated by Django 5.2 on 2025-07-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Plan Adı')),
                ('google_product_id_monthly', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google Play Aylık ID')),
                ('google_product_id_yearly', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google Play Yıllık ID')),
                ('apple_product_id_monthly', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='App Store Aylık ID')),
                ('apple_product_id_yearly', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='App Store Yıllık ID')),
                ('max_tables', models.PositiveIntegerField(default=10, verbose_name='Maks. Masa Sayısı')),
                ('max_staff', models.PositiveIntegerField(default=2, verbose_name='Maks. Personel Sayısı')),
                ('max_kds_screens', models.PositiveIntegerField(default=2, verbose_name='Maks. KDS Ekranı')),
                ('max_categories', models.PositiveIntegerField(default=4, verbose_name='Maks. Kategori Sayısı')),
                ('max_menu_items', models.PositiveIntegerField(default=20, verbose_name='Maks. Menü Ürünü')),
                ('max_variants', models.PositiveIntegerField(default=50, verbose_name='Maks. Ürün Varyantı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Seçilebilir mi?')),
            ],
            options={
                'verbose_name': 'Abonelik Planı',
                'verbose_name_plural': 'Abonelik Planları',
                'ordering': ['max_tables'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('trial', 'Deneme Süresinde'), ('inactive', 'Pasif (Süre Doldu/Ödenmedi)'), ('cancelled', 'İptal Edildi')], default='trial', max_length=20, verbose_name='Durum')),
                ('provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sağlayıcı (Google/Apple)')),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sağlayıcı Abonelik ID')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.business')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.plan', verbose_name='Abonelik Planı')),
            ],
            options={
                'verbose_name': 'İşletme Aboneliği',
                'verbose_name_plural': 'İşletme Abonelikleri',
            },
        ),
    ]
